version: '3.8'
services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000/chatbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
